# Generated by Django 5.0 on 2023-12-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userData2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.PositiveBigIntegerField()),
                ('img', models.ImageField(blank=True, upload_to='userimg/')),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
