# Generated by Django 5.0 on 2023-12-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodelapp', '0002_userdata2'),
    ]

    operations = [
        migrations.CreateModel(
            name='updateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveBigIntegerField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
