# Generated by Django 5.0 on 2023-12-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodelapp', '0003_updatedata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='updateData',
        ),
        migrations.DeleteModel(
            name='userData2',
        ),
        migrations.AddField(
            model_name='userdata',
            name='address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='img',
            field=models.ImageField(blank=True, upload_to='userimg/'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='phone',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
