# Generated by Django 5.0 on 2023-12-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermodelapp', '0005_userdata_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='name',
        ),
    ]
